overrides:
  - files: "*.sol"
    options:
      bracketSpacing: false
      printWidth: 120
      tabWidth: 4
      useTabs: false
      singleQuote: false
      explicitTypes: always
  - files: "*.ts"
    options:
      printWidth: 120
      semi: true
      trailingComma: all

